/* eslint-disable react/no-unknown-property */
import {useState, useEffect} from 'react';
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Heading, Text } from "@chakra-ui/layout";
import { Progress } from "@chakra-ui/react"
import GratitudeNoteCreator from "../src/features/GratitudeNoteCreator";
import SideBar from '../src/SideBar';
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [progress, setProgress] = useState(0);
  const [step, setStep] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300;400;700&display=swap" rel="stylesheet"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <SideBar /> */}
        {/* <Progress value={10} w="100%" maxW="550px" mb={10} borderRadius={10}/> */}
        <Heading as="h1" fontSize="6xl">Gratitude journal</Heading>
        <Heading as="p" fontSize="3xl" maxW="550px" mb={10} textAlign="center" color="gray.700">
          A gratitude journal is, quite simply, a tool to keep track of the good
          things in life. No matter how difficult and defeating life can
          sometimes feel, there is always something to feel grateful for.
        </Heading>
        <GratitudeNoteCreator />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
